# github: [nu11secur1ty]
patreon: nu11secur1ty
custom: ["https://www.patreon.com/posts/33851174", patreon.com]
custom: ["https://github.com/nu11secur1ty/Linux_hardening_and_security/tree/master/Protect_MySQL"]
